version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123456
      MYSQL_DATABASE: theadvertisers
      TZ: Asia/Kolkata
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  app:
    build: .
    container_name: advertisers-app
    restart: always

    depends_on:
      mysql:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/theadvertisers
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@123456

    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: