spring.application.name=The-Advertisers
server.port=8080

#Aiven Console Database Configurations -

## Database Configuration
#Oracle Mysql -
spring.datasource.url=jdbc:mysql://80.225.216.150:3306/theadvertisers
spring.datasource.username=root
spring.datasource.password=Root@123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.email.ap-mumbai-1.oci.oraclecloud.com
spring.mail.port=587
spring.mail.username=ocid1.user.oc1..aaaaaaaa6tgkjxgy35kppahoqkyqedwrdr66dsl4vr3nfr74i2lhnbrop6bq@ocid1.tenancy.oc1..aaaaaaaa6l7vpep4rop76e4q4ouz7fysgmm3kzsunj7whm3ixain5yhuimua.zt.com
spring.mail.password={}mWZMhzVh2J$y8;:5q&
